FROM alpine

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

RUN set -eux; \
  echo "TARGETPLATFORM=$TARGETPLATFORM"; \
  echo "TARGETOS=$TARGETOS"; \
  echo "TARGETARCH=$TARGETARCH"; \
  echo "TARGETVARIANT=$TARGETVARIANT"; \
  echo "BUILDPLATFORM=$BUILDPLATFORM"; \
  echo "BUILDOS=$BUILDOS"; \
  echo "BUILDARCH=$BUILDARCH"; \
  echo "BUILDVARIANT=$BUILDVARIANT";


